### PR TITLE
Support for multi region(swarm clusters)  with many hosts/multi subnets launching time sliced container

### PR DESCRIPTION
**Pull request by ranjithamca**

### CODE REVIEW

**Comment by indykish** [comment]
@ranjithamca  Great job ! .

**Comment by indykish** [comment]
@ranjithamca  Educate @rajesh-rajagopal  and setup multi cluster to test it (syndey/chennai) + prod africa -dar_e_salaam.

**Comment by indykish** [comment]
@vijaykanthm28  Review and let me know, as you had worked on the same support for One (multi region cluster)

**Comment by vijaykanthm28** [comment]
@indykish verified

**Comment by indykish** [comment]
@vijaykanthm28  Thanks for the review.

**Comment by indykish** [comment]
@rajesh-rajagopal  Build and update vertice, ready it up for africa.

**Pull request merged**
